name: Auto PR
on:
  push:
    branches-ignore:
    - master
    - development

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: create-pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "development"
